CREATE TABLE custom_levels (
    id INT AUTO_INCREMENT PRIMARY KEY,
    characterName VARCHAR(255),
    Attack INT,
    Defence INT,
    Strength INT,
    Magic INT,
    Range INT,
    Hitpoint INT,
    Prayer INT,
    Woodcutting INT,
    Fishing INT,
    Cooking INT,
    Firemaking INT,
    Crafting INT,
    Smithing INT,
    Mining INT,
    Herblore INT,
    Agility INT,
    Thieving INT,
    Slayer INT,
    Farming INT,
    Runecrafting INT
);
